version: '3'
services:
  redis:
    container_name: acnelog-redis
    image: redis:7.0.11
    ports:
      - "6379:6379"
    networks:
      - acnelog-network
  postgresql:
    container_name: acnelog-postgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_test
    networks:
      - acnelog-network

networks:
  acnelog-network:
    driver: bridge
